services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
